### ISSUE TITLE
Disable BlazeDS / Flash Remoting by default

### ISSUE THREAD

**Issue by pfreitag** [utdream/lucee-installer#73]
In the current state it looks like the Lucee installer has disabled (commented out) the Flash Remoting servlets and servlet-mappings for Tomcat 8 web.xml but the Tomcat 7 web.xml still has it enabled. Not sure if the tomcat 7 is used anymore (is there an option to pick tomcat version?) but if so, then consider disabling it by default (due to security issues and the fact that not many people use it anymore). It should also improve server startup times.

More info: https://www.petefreitag.com/item/837.cfm and https://luceeserver.atlassian.net/browse/LD-72

**Comment by utdream** [comment]
Thanks Pete. There's no option to pick the Tomcat version and Tomcat 7 will no longer be included now that we're on Tomcat 8 (too much work!). Thanks for letting me know. I'll try to help spread the word.

**Comment by utdream** [comment]
Removing tomcat 7 files from repo for Lucee 5
