### ISSUE TITLE
Remove superfluous proxy config from install_mod_proxy.sh

### ISSUE THREAD

**Issue by utdream** [utdream/lucee-installer#80]
Jamie Jackson pointed out via Slack that the <Proxy *> block of code that the 'install_mod_proxy.sh' script installs doesn't really have a purpose, and that does indeed appear to be the case. I cannot think of any reason why that block of code needs to be there. Needs to be tested and probably removed.

**Comment by jamiejackson** [comment]
To be specific:

```xml
		<Proxy *>
			Allow from 127.0.0.1
		</Proxy>
```

**Comment by utdream** [comment]
Tested, removed and prepped for next installer release.

**Comment by utdream** [comment]
Not sure how. This made it into the latest build. Need to remove.

**Comment by utdream** [comment]
lol. No, it's still gone. Someone on the list was just adding it again for whatever reason.
