### ISSUE TITLE
update tomcat and java versions

### ISSUE THREAD

**Issue by zspitzer** [utdream/lucee-installer#87]
Bundled versions are rather out of date

- Java is 1.8.0_131, latest is 1.8.0_144
- Tomcat is 8.0.32, latest is 8.0.46 but 8.0.x is EOL http://tomcat.apache.org/tomcat-80-eol.html

Perhaps Tomcat 8.5.20 ? 
http://tomcat.apache.org/tomcat-8.5-doc/changelog.html#Tomcat_8.5.20_(markt)

**Comment by utdream** [comment]
Hi Zac,

Bundled versions of software are updated almost every release. I keep track of it here:
https://github.com/utdream/lucee-installer/wiki/Lucee-Installer-Release-Notes
